### ISSUE TITLE
Critical Error: Function recursion limit exceeded.

### ISSUE THREAD

**Issue by DMD-x** [SaifAqqad/AHK_MicMute#83]
![image](https://user-images.githubusercontent.com/120769710/208226022-dbeb7575-439a-4d24-929d-b22ec14a5edf.png)

it started happening lately for some reason

**Comment by SaifAqqad** [comment]
@DMD-x Can you post the contents of your `config.json` file?

To open it, just hold <kbd>Shift</kbd> when clicking `Edit Configuration` in the tray menu

**Comment by DMD-x** [comment]
@SaifAqqad 
![image](https://user-images.githubusercontent.com/120769710/208972289-66b9807c-2f03-4c1a-aaf1-8695bdce4403.png)

**Comment by SaifAqqad** [comment]
@DMD-x commit ef12ddd1267e7ce99395642935f45b5f4ea652f1 should fix this issue, you can test it in the pre-release build [here](https://github.com/SaifAqqad/AHK_MicMute/releases/tag/latest_commit)

**Comment by DMD-x** [comment]
unfortunately, still the same issue but different error code:

![image](https://user-images.githubusercontent.com/120769710/213845569-b01db239-cdee-481e-a276-e0bc77305414.png)

the config screenshot:

![image](https://user-images.githubusercontent.com/120769710/213845592-6b74a6ed-eba0-4bf7-ae11-8f9d8d9ad36a.png)

**Comment by SaifAqqad** [comment]
that's really weird, and unfortunately I can't reproduce it any more

**Comment by SaifAqqad** [comment]
@DMD-x commit d1fed34a50ead9d36031b28ee3ed98e1991d831d should definitely fix it

You can test it in the latest [pre-release](https://github.com/SaifAqqad/AHK_MicMute/releases/tag/latest_commit)

**Comment by DMD-x** [comment]
Thanks a lot it works finally!
